# Generated by Django 4.2.3 on 2023-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.TextField(choices=[('honda city', 'honda city'), ('honda civic', 'honda civic'), ('toyota corolla', 'toyota corolla'), ('honda brv', 'honda brv'), ('toyota vitz', 'toyota vitz'), ('toyota aqua', 'toyota aqua'), ('toyota yaris', 'toyota yaris'), ('hyundai elantra', 'hyundai elantra'), ('changan alsvin', 'changan alsvin'), ('KIA Sportage', 'KIA Sportage'), ('Toyota Fortuner', 'Toyoyta Fortuner'), ('Toyota Landcruiser', 'Toyota Landcruiser'), ('Toyota Landcruiser Prado', 'Toyota Landcruiser Prado'), ('MG HS', 'MG HS'), ('Hyundai Tucson', 'Hyundai Tucson'), ('Toyota Hilux', 'Toyota Hilux'), ('Honda Vezel', 'Honda Vezel'), ('Oshan X7', 'Oshan X7'), ('Cardillac Limousine', 'Cardillac Limousine'), ('Mercedes Benz', 'Mercedes Benz'), ('Rolls Royce Phantom', 'Rolls Royce Phantom'), ('BMW 5 series', 'BMW 5 series'), ('Audi A series', 'Audi A series'), ('BMW 7 series', 'BMW 7 series'), ('Toyota Tundra', 'Toyota Tundra'), ('Nissan 350z', 'Nissan 350z'), ('Lamborghini Aventador', 'Lamborghini Aventador')], default='select', max_length=50),
        ),
    ]
